### ISSUE TITLE
wav.wav

### ISSUE THREAD

**Issue by xczhusuda** [wenet-e2e/wesep#12]
您好，我们在运行wesep/examples/voxceleb1/v2训练程序时出现了以下报错
我们在路径下并未找到wav.wav文件
[ WARNING : 2024-10-21 19:50:35,874 ] - error to parse id10415/Pugs1qQcG04/00008.wav.wav
[ WARNING : 2024-10-21 19:50:35,875 ] - error to parse id11077/lI_uBKwrleY/00001.wav.wav
[ WARNING : 2024-10-21 19:50:35,876 ] - error to parse id11041/uL1-ymIrlv8/00009.wav.wav
[ WARNING : 2024-10-21 19:50:35,876 ] - error to parse id10564/XaCmErdA2sM/00062.wav.wav
[ WARNING : 2024-10-21 19:50:35,877 ] - error to parse id10393/sV_ohWbzzQg/00008.wav.wav
[ WARNING : 2024-10-21 19:50:35,878 ] - error to parse id11248/QdBQTHX55yI/00019.wav.wav
[ WARNING : 2024-10-21 19:50:35,878 ] - error to parse id11007/6pWSEcQvPU4/00003.wav.wav
[ WARNING : 2024-10-21 19:50:35,879 ] - error to parse id10080/6x6ZSpvDezc/00001.wav.wav
[ WARNING : 2024-10-21 19:50:35,880 ] - error to parse id10742/eG6pQulY59E/00004.wav.wav
[ WARNING : 2024-10-21 19:50:35,881 ] - error to parse id10520/C71m6GwhtrE/00006.wav.wav
[ WARNING : 2024-10-21 19:50:35,881 ] - error to parse id10235/4Ce3PM-4tRE/00005.wav.wav
[ WARNING : 2024-10-21 19:50:35,882 ] - error to parse id10908/dG53U3yrdCE/00033.wav.wav
[ WARNING : 2024-10-21 19:50:35,882 ] - error to parse id10054/yw31dqC_oCk/00004.wav.wav

**Comment by mrjunjieli** [comment]
Please see [issue]( https://github.com/wenet-e2e/wesep/issues/4)

**Comment by xczhusuda** [comment]
> 请参阅[问题](https://github.com/wenet-e2e/wesep/issues/4)

您好！请问为什么torch version>2.0会出现这样.wav.wav的问题呢，很奇怪。后续wesep会优化这部分问题吗？

**Comment by mrjunjieli** [comment]
如果你想在torch version>2的情况使用 参考 https://github.com/wenet-e2e/wespeaker/issues/338
