### ISSUE TITLE
some problem occured when train

### ISSUE THREAD

**Issue by wendongj** [wenet-e2e/wesep#4]
Dear, author, thanks for your great work. when I try to train the model, it have many warning like this: error to parse id10536/aZT_gTu6ilw/00005.wav.wav. I check the voxceleb dataset seems ok, did you have encounter such problem before?

I check the wav.scp file seems ok, it like follows:
id10001/1zcIwhmdeo4/00001.wav /home/jwd/code/dataset/voxceleb/VoxCeleb1/wav/id10001/1zcIwhmdeo4/00001.wav

**Comment by mrjunjieli** [comment]
Hi, Maybe you could try to use torch version<2.0.  In my case it works.

**Comment by wendongj** [comment]
> Hi, Maybe you could try to use torch version<2.0. In my case it works.

I see, thanks, I will try it
