### ISSUE TITLE
RuntimeError: DataLoader worker (pid 123140) is killed by signal: Killed

### ISSUE THREAD

**Issue by yezhangyinge** [wenet-e2e/wesep#5]
[train.log](https://github.com/user-attachments/files/16957291/train.log)
Hello, I am training example of Libri2Mix v2 using multi GPUs but I met some problems. So I add the error in the log file(I don't know why the log do not contain error) and upload it. Could you please give me some advise? Thanks!

**Comment by mrjunjieli** [comment]
1. Have you ever tried to train using only one GPU? 
2. If it still doesn't work, you can try adjusting pytorch version <2.0. 
Hope it helps.

**Comment by yezhangyinge** [comment]
1. I had trid to train using only one GPU, but the process will stop after some iterations.
2. My pytorch version is 1.12.1, which is already <2.0

**Comment by mrjunjieli** [comment]
Still don't have any error information in log when training in single GPU?

**Comment by yezhangyinge** [comment]
Sorry for the delay. This is the train.log when training in single GPU.
[train.log](https://github.com/user-attachments/files/16990124/train.log)

**Comment by wsstriving** [comment]
It seems like the issue might be with your server environment. Do you have enough CPUs available? Try setting a smaller value for num_worker.

**Comment by yezhangyinge** [comment]
> It seems like the issue might be with your server environment. Do you have enough CPUs available? Try setting a smaller value for num_worker.

Thanks! It's a really helpful suggestion! I try num_worker = 2 and it works on both single GPU and multi GPUs.
