### ISSUE TITLE
About discussion group

### ISSUE THREAD

**Issue by yezhangyinge** [wenet-e2e/wesep#8]
Hello, I am using this great project for research and I want to have some discussions with other people who is also interesting in TSE. So is there any WeChat group? Thanks!

**Comment by mrjunjieli** [comment]
Hi, thanks for your attention on this toolkit and your suggestions. We will start a Wechat group in a few days.

**Comment by yezhangyinge** [comment]
Thanks for your reply. But I have some problems:
1. In this code I didn't see any Norm funciton of the input audio (like cumulative layer norm, forgetting norm), why not use? Could you give me some advise?
2. when I set the num_repeat = 1 in BSRNN, the network works pretty bad (loss is too large) and when I set num_repeat = 3, the network work quite well. And after I add a norm function in the BSRNN (num_repeat=1), the network become working (loss can reach -6dB). Why is this happening?

**Comment by mrjunjieli** [comment]
You could find QR Code of our Wechat group in README.md.

**Comment by yezhangyinge** [comment]
thanks!
